# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=250, verbose_name=b'Full Name')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name=b'Username')),
                ('password', models.CharField(max_length=128, verbose_name=b'Password')),
                ('email', models.CharField(max_length=128, unique=True, verbose_name=b'Email')),
                ('description', models.TextField(verbose_name=b'Description')),
                ('website', models.CharField(max_length=128, verbose_name=b'Website')),
                ('active', models.BooleanField(default=False, verbose_name=b'Active')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
