# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email@email.com', max_length=128, unique=True, verbose_name=b'Email'),
            preserve_default=False,
        ),
    ]
