# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160626_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tags',
        ),
    ]
